version: '3.8'

services:
  eureka-server:
    build: ./EurekaService
    container_name: fipkart-eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-network

  postgres-db:
    image: postgres:latest
    container_name: pgsql-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - spring-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # SQL script to create multiple databases

  user-service:
    build: ./UserService
    container_name: fipkart-user-service
    depends_on:
      - eureka-server
      - postgres-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8081:8081"
    networks:
      - spring-network

  order-service:
    build: ./OrderService
    container_name: fipkart-rder-service
    depends_on:
      - eureka-server
      - postgres-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8082:8082"
    networks:
      - spring-network

volumes:
  postgres-data:

networks:
  spring-network:
    driver: bridge
