server:
  port: 8082

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/order_db"
    username: "postgres"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
